### ISSUE TITLE
iMonke js client issue

### ISSUE THREAD

**Issue by TobiWtf** [gastrodon/iMonke.js#1]
```js
const accountObject = async () => {
    var storage = new storageModule();
    let login = await storage.GetLogin();
    let client = new imonke.Client({email: login.email, secret: login.secret});
    let user = await client.data;
    let profileBox = await makeDiv();
```

In this bit of code, it should initialize the client with that secret, without refreshing the auth.

Now, i may need to do a bit of testing, but i believe, as soon as the client module is initialized, it runs the auth endpoint.

You can see in this image, the request successfully goes through.

![Screenshot from 2020-11-28 17-23-57](https://user-images.githubusercontent.com/63171481/100528118-b66b2100-319e-11eb-9f9e-da0a93fcbc4d.png)

The problem is, this creates a new secret, which in theory updates the secret of the client, im pretty sure the fix for me needs to be that as soon as i make a new client, it stores the data of the new client and replaces the old data. Either way, i don't think it should make a auth request every time its initialized.

**Comment by gastrodon** [comment]
> this creates a new secret, which in theory updates the secret of the client, im pretty sure the fix for me needs to be that as soon as i make a new client, it stores the data of the new client and replaces the old data

This is expected behavior

**Comment by TobiWtf** [comment]
> > this creates a new secret, which in theory updates the secret of the client, im pretty sure the fix for me needs to be that as soon as i make a new client, it stores the data of the new client and replaces the old data
> 
> This is expected behavior

Whether expected behavior it's not good behavior. The option to pass a token as an argument rather than void the old secret should be allowed.

**Comment by gastrodon** [comment]
I disagree, a client with only a token has no way to refresh its token, which makes it impossible to have persistent auth. This is antithetical to the point of a Client class that manages its auth, and to the point of the API not allowing multiple secrets or tokens to be bound to an account
